apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi-deployment
  labels:
    app: tripInsights
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poi-1.0
  template:
    metadata:
      labels:
        app: poi-1.0
    spec:
      containers:
      - name: poi
        image: registrypek4427.azurecr.io/poi:1.0
        env:
        - name: SQL_USER
          valueFrom: 
            secretKeyRef:
              name: db-user-pass
              key: SQL_USER
              optional: false
        - name: SQL_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: db-user-pass
              key: SQL_PASSWORD
              optional: false
        - name: SQL_SERVER
          valueFrom: 
            secretKeyRef:
              name: db-user-pass
              key: SQL_SERVER
              optional: false
        - name: SQL_DBNAME
          valueFrom: 
            secretKeyRef:
              name: db-user-pass
              key: SQL_DBNAME
              optional: false
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: poi-service
  labels:
    run: poi-service
spec:
  ports:
  - protocol: TCP
    name: http
    port: 8080
    targetPort: 80
  selector:
    app: poi-1.0

