apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi-deployment
  labels:
    app: tripInsights
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poi-1.0
  template:
    metadata:
      labels:
        app: poi-1.0
    spec:
      containers:
      - name: poi
        image: registrypek4427.azurecr.io/poi:1.0
        env:
        - name: SQL_USER
          value: "sqladminpEk4427"
        - name: SQL_PASSWORD
          value: "mC5fp1Xi8"
        - name: SQL_SERVER
          value: "sqlserverpek4427.database.windows.net"
        - name: SQL_DBNAME
          value: "mydrivingDB"
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        ports:
        - containerPort: 80
