apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripviewer-deployment
  namespace: web
  labels:
    app: tripInsights
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tripviewer-1.0
  template:
    metadata:
      labels:
        app: tripviewer-1.0
    spec:
      containers:
      - name: tripviewer
        image: registrypek4427.azurecr.io/tripviewer:1.0
        env:
        - name: TRIPS_API_ENDPOINT
          value: "http://trips-service.api.svc.cluster.local:8080"
        - name: USERPROFILE_API_ENDPOINT
          value: "http://userprofile-service.api.svc.cluster.local:8080"
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: tripviewer-service
  namespace: web
  labels:
    run: tripviewer-service
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    name: http
    port: 8080
    targetPort: 80
  selector:
    app: tripviewer-1.0

