apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-java-deployment
  namespace: api
  labels:
    app: tripInsights
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-java-1.0
  template:
    metadata:
      labels:
        app: user-java-1.0
    spec:
      containers:
      - name: user-java
        image: registrypek4427.azurecr.io/user-java:1.0
        ports:
        - containerPort: 80
        volumeMounts:
        - name: secrets-store01-inline
          mountPath: "/secrets"
          readOnly: true
      volumes:
        - name: secrets-store01-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "azure-kvname-user-msi"

---

apiVersion: v1
kind: Service
metadata:
  name: user-java-service
  namespace: api
  labels:
    run: user-java-service
spec:
  ports:
  - protocol: TCP
    name: http
    port: 8080
    targetPort: 80
  selector:
    app: user-java-1.0

