apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-java-deployment
  namespace: api
  labels:
    app: tripInsights
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-java-1.0
  template:
    metadata:
      labels:
        app: user-java-1.0
    spec:
      containers:
      - name: user-java
        image: registrypek4427.azurecr.io/user-java:1.0
        env:
        - name: SQL_USER
          valueFrom: 
            secretKeyRef:
              name: db-user-pass
              key: SQL_USER
              optional: false
        - name: SQL_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: db-user-pass
              key: SQL_PASSWORD
              optional: false
        - name: SQL_SERVER
          valueFrom: 
            secretKeyRef:
              name: db-user-pass
              key: SQL_SERVER
              optional: false
        - name: SQL_DBNAME
          valueFrom: 
            secretKeyRef:
              name: db-user-pass
              key: SQL_DBNAME
              optional: false
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: user-java-service
  namespace: api
  labels:
    run: user-java-service
spec:
  ports:
  - protocol: TCP
    name: http
    port: 8080
    targetPort: 80
  selector:
    app: user-java-1.0

